# Generated by Django 5.0.1 on 2024-01-09 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contactsapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="createed_at",
            new_name="created_at",
        ),
    ]
